plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'bin/*'

# Style preferences for this project
Style/Documentation:
  Enabled: false  # We use self-documenting code

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

# Layout preferences
Layout/LineLength:
  Max: 120
  Exclude:
    - 'test/**/*'  # Tests can have longer lines for readability

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Metrics - reasonable for a CLI tool
Metrics/MethodLength:
  Max: 45  # Allow longer methods for complex CLI operations
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 200
  Exclude:
    - 'test/**/*'

Metrics/AbcSize:
  Max: 45  # Allow higher complexity for CLI argument parsing
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 25  # Allow higher complexity for CLI operations

Metrics/PerceivedComplexity:
  Max: 25  # Allow higher complexity for CLI operations

Metrics/ParameterLists:
  Max: 8  # Allow more parameters for CLI methods

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'
    - '*.gemspec'
    - 'Rakefile'

# Naming
Naming/FileName:
  Exclude:
    - 'lib/auto-claude.rb'  # Entry point uses hyphen

# Minitest specific
Minitest/MultipleAssertions:
  Max: 20  # Allow more assertions in comprehensive test cases

Minitest/AssertEmptyLiteral:
  Enabled: false  # We sometimes prefer assert_equal [] for clarity

# Project-specific exclusions
Lint/MissingSuper:
  Exclude:
    - 'lib/auto_claude/output/*.rb'  # Output writers don't need super
    - 'examples/**/*'  # Examples may have custom classes

Lint/UnusedMethodArgument:
  Enabled: true  # No exclusions needed after V1 removal

Style/FormatString:
  Enabled: false  # We prefer String#% for simple formatting

Gemspec/DevelopmentDependencies:
  Enabled: false  # We specify dev dependencies in gemspec

Lint/IneffectiveAccessModifier:
  Exclude:
    - 'lib/auto_claude/messages/base.rb'  # Class methods protection pattern

